name: Unit, Integration and Acceptance Tests on Main push

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest discover -s test -p '*_unit.py'

  run-integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: [run-unit-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Integration tests
        run: |
          python -m unittest discover -s test -p '*_integration.py'

  run-acceptance-tests:
    name: Run Acceptance Tests
    runs-on: ubuntu-latest
    needs: [ run-unit-tests, run-integration-tests ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Acceptance tests
        run: |
          python -m unittest discover -s test -p '*_acceptance.py'